### ISSUE TITLE
After I click on deploy on netlify, my github repo fork is empty

### ISSUE THREAD

**Issue by hansugu** [stackrole/gatsby-starter-foundation#2] opened 2020-07-14 05:00 UTC
deployment is successful but the repo is empty. So CMS cannot be used

https://github.com/hansugu/gatsby-homepage

**Comment by stackrole-dev** [comment] 2020-07-15 05:45
Hi Hansugu,

You might be looking at the wrong location. I found the repo forked here https://github.com/hansugu/gatsby-starter-foundation.

Let me know if that resolves this issue

**Comment by hansugu** [comment] 2020-07-15 15:42
Thanks for getting back to me. This is a manual fork on github and then manual changes in netlify settings. The deployment button still does not work. I recommend some testing on a different github account and you will see what happened to me. Great website and code by the way.

**Comment by stackrole-dev** [comment] 2020-07-15 16:06
You might run into this problem, if you are trying to fork a repo which has the same name as your already existing repos.

I have tried this from my end, could not reproduce the issue.

Can you please check once and help reproduce. So we could look deeper into the issue

**Comment by munwr** [comment] 2020-07-22 08:24
This issue has gone spooky quite, so closing it. Feel free to reopen as needed

**Comment by munwr** [comment] 2020-07-22 08:25
This issue have gone spooky quite. So, closing it. Feel free to reopen as needed

**Comment by philww241** [comment] 2020-07-26 18:07
Reopening this as I had the same problem today as hansugu reported. I clicked on 'Deploy to Netlify', and the site was published on Netlify, but the repo created in my Github account was empty and the admin access to the Netlify CMS didn't work. (Guessing here, but is is possible the deployment came directly from this stackrole repo rather than creating a new one in my Github account first?)

I then tried doing a manual fork of the stackrole repo to my own account, and when I connected this to Netlify, I could access the Netlify CMS. But now that I have edited the content and those changes are appearing in my Master branch, when I go to do a pull request, it wants to merge the changes into the Main branch here, which obviously is not what I want to do. So I have deleted my Netlify site (but not the Github yet repo) until I can figure out or get some help on what's going wrong here.

**Comment by munwr** [comment] 2020-07-27 14:43
1. Here is how **Deploy to Netlify** works:
When the button is clicked, it would you to Netlify Direct Deploy page, Ask you to create an account then ask for the name of the repo you want to create. In between this process, it would as you give write access so Netlify could create a repo and add code to it. If this permission is any chance missed. The repo might fail to fork under your username.

If you suspect this wait until the build is finished at Netlify and look for following in Netlify Deploy Log.
`Error pushing to remote repository at git@github.com:[username]/[repo]`

You can fix this by going into Netlify > User Settings [from profile pic] and reconnect github permissions

**Closed by munwr** 2020-07-27 14:43 UTC

**Comment by munwr** [comment] 2020-07-27 14:46
@philww241 I have also fixed new posts coming into `master` branch. Now you dont need to merge, all posts will be created in `main` itself. Just pull my latest changes

**Comment by stackrole-dev** [comment] 2020-07-27 15:27
Thank @hansugu and @philww241 for reporting this, i have fixed all the issues regarding "Deploy to Netlify". The main cause was Github actions that were preventing Netlify to fork into the repos.

No action needed from your end. You can enjoy deployment with a click :)
